apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: dgfip/ask-your-document-api
          env:
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: minio-endpoint
            - name: MINIO_COLLECTIONS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: minio-collections-bucket-name
            - name: OPENAI_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: openai-api-base
            - name: OPENAI_API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: openai-api-version
            - name: QDRANT_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: qdrant-endpoint
            - name: QDRANT_BASE_COLLECTION_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: qdrant-base-collection-name
            - name: NO_PROXY
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: no-proxy
            - name: RAG_PRECISION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: rag-precision
            - name: MODELS
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: models
            - name : MLFLOW_URI
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: mlflow-uri 
            - name : PROMPT_FILE_PATH
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: prompt-file-path
            - name: LOGGER_PATH
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: logger-path
            - name: LOGGER_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: logger-level
            - name: LOGGER_RETENTION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: logger-retention
            - name: LOGGER_ROTATION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: logger-rotation
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: minio-access-key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: minio-secret-key
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: openai-api-key
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: mongo-username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: mongo-password
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: mongodb-uri
            - name: MONGODB_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: mongodb-database-name

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8100  # service port
      targetPort: 8100  # container port to forward requests to